function Voltage=convert_voltage(counts);
%
VOLTAGE_CONSTANT_1= 3.3;
VOLTAGE_CONSTANT_2= 4095.0;
VOLTAGE_CONSTANT_3= 5.0151;
VOLTAGE_CONSTANT_4= 0.6301;
Voltage = ((counts * VOLTAGE_CONSTANT_1)/VOLTAGE_CONSTANT_2) * VOLTAGE_CONSTANT_3 + VOLTAGE_CONSTANT_4;